InconfontFlag: true

default:
  avatar: /img/default/avatar.svg
  link: /img/default/link.svg
  cover: /img/default/cover.svg
  image: /img/default/image.svg

cdn:
  enable: true
  prefix: https://static.inkss.cn
  set:
    js:
      app: /js/app.js
      rightMenu: /js/plugins/rightMenu.js
      rightMenus: /js/plugins/rightMenus.js
      iconfontInkss: /js/thirdparty/iconfontInkss.js
    css:
      style: /css/style.css

navbar:
  logo:
      img:
      title: INKSS
  search: 想找些什么~
  menu:
    - name: 首页
      icon: fa-duotone fa-home CARROT faa-vertical
      url: /
    - name: 导航
      icon: fa-duotone fa-cube NEPHRITIS
      rows:
        - name: 分类列表
          icon: fa-duotone fa-folder-open TURQUOISE faa-vertical
          url: /categories/
        - name: 文章归档
          icon: fa-duotone fa-archive PETERRIVE faa-vertical
          url: /archives/
        - name: 个人笔记
          icon: fa-duotone fa-books CARROT faa-vertical
          url: /page/notes/
    - name: 功能
      icon: fa-duotone fa-anchor GREENSEA faa-vertical
      rows:
        - name: 站内留言
          icon: fa-duotone fa-hand-love ALIZARIN faa-vertical
          url: /page/info/
        - name: RSS 订阅
          icon: fa-duotone fa-rss SUNFLOWER faa-vertical
          url: /page/atom/
        - name: Start 列表
          description: 有用的开源软件列表
          icon: fa-duotone fa-star-half-alt WISTERIA faa-vertical
          url: /page/start/
    - name: 更多
      icon: fa-duotone fa-umbrella POMEGRANATE faa-vertical
      description: 站外资源列表
      rows:
        - name: BT 
          description: 宝塔面板
          icon: fa-duotone fa-spider-web SUNFLOWER faa-vertical
          url: https://web.adc.ink/
        - name: Github
          description: 少年，来一份星星不？
          icon: fa-duotone fa-code-merge WISTERIA faa-vertical
          url: https://github.com/inkss
        - name: Blog
          description: 这是一份记录文字的博客站点
          icon: fa-duotone fa-stream BELIZEHOLE faa-vertical
          url: https://szyink.com
    - name: 虫洞
      description: 十年之约，探索虫洞
      icon: fa-duotone fa-bullseye-pointer BELIZEHOLE faa-vertical
      url: https://www.foreverblog.cn/go.html

cover:
  height_scheme: full
  layout_scheme: blank
  display:
    home: false
    archive: false
    others: false
  background: /img/bkg/wallhaven-8oj7wk.png
  search: 想找些什么？
  features:
    - name: 关于
      icon: fa-duotone fa-drafting-compass
      url: /page/about/
    - name: 友链
      icon: fa-duotone fa-stamp
      url: /page/friends/
    - name: 留言
      icon: fa-duotone fa-comment-alt-smile
      url: /page/info/
    - name: 归档
      icon: fa-duotone fa-archive
      url: /archives/

pages:
  friends:
    layout_scheme: traditional 

article:
  preview:
    line_style: hidden
  body:
    top_meta: [author, wordcount, updated]
    bottom_meta: [category, tags, date, counter]
    meta_library:
      author:
        avatar: https://static.inkss.cn/img/avatar.jpg
        name: 枋柚梓
        url: /
      date:
        icon: fa-duotone fa-calendar-alt TURQUOISE
      updated:
        icon: fa-duotone fa-edit GREENSEA
      category:
        icon: fa-duotone fa-folder-open EMERALD
      counter:
        icon: fa-duotone fa-eye NEPHRITIS
      valinecount:
        icon: fa-duotone fa-comment-dots NEPHRITIS
      walinecount:
        icon: fa-duotone fa-comment-dots NEPHRITIS
      wordcount:
        icon_wordcount: fa-duotone fa-keyboard PETERRIVE
        icon_duration: fa-duotone fa-hourglass-half BELIZEHOLE
      tags:
        icon: fa-duotone fa-hashtag CARROT
    footer_widget:
      references:
        icon: fa-duotone fa-quote-left CONCRETE
      copyright:
        enable: true
        content:
          - '博客内容遵循 <a href="/page/cc">署名-相同方式共享 4.0 国际 (CC BY-SA 4.0)</a> 协议。'

comments:
  title: <i class='fa-duotone fa-comments POMEGRANATE'></i> 评论
  service: artalk
  disqus:
    shortname: inkss
  twikoo:
    js: https://static.szyink.com/common/js/twikoo.js # 建议锁定版本 v1.4.4
    envId: twikoo-web-4g84uta0261cb889 # 腾讯云环境id
  beaudar:
    repo: inkss/blog-comments
    branch: master
  artalk:
    js: https://artalk.szyink.com/dist/Artalk.js
    css: https://artalk.szyink.com/dist/Artalk.css
    server: https://artalk.szyink.com

sidebar:
  for_page: [blogger, notice, navigation, lastupdate, webinfo]
  for_post: []
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.jpg
      shape: circle # circle, rectangle
      url: /page/about/
      title:
      subtitle: 言语道断，非物所拘。
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fa-duotone fa-clock WISTERIA
        title: 最近更新
    toc:
      display: [desktop, mobile]
      header:
        icon: fa-duotone fa-list ASBESTOS
    category:
      display: [desktop]
      header:
        icon: fa-duotone fa-folder-open ASBESTOS
        url: /categories/
    tagcloud:
      display: [desktop]
      header:
        title: 标签列表
        icon: fa-duotone fa-tags WISTERIA 
        url: /tags/
      max_font: 24
      min_font: 16
    webinfo:
      display: [desktop]
      header:
        icon: fa-duotone fa-award NEPHRITIS
      type:
        runtime:
          data: '2018/03/15'
        wordcount:
          unit: ''
        visitcounter:
          siteuv:
            enable: false
          sitepv:
            enable: false
    notice:
      class: text
      display: [desktop]
      header:
        icon: fa-duotone fa-ghost PETERRIVE 
        title: 公共信息
      content:
        - '嘿，这里是枋柚梓的笔记站，主要是用于记录一些偏专业向的内容，生活向内容请见：[枋柚梓的博客](https://szyink.com/)。'
        - '<a href="https://www.foreverblog.cn/go.html" target="_blank" style="margin-right: 6px;"><img src="/img/default/wormhole.gif" alt="虫洞" style="width:auto;height:31px;border-radius:4px;" title="穿梭虫洞-随机访问十年之约友链博客"></a><a href="/page/cc"><img src="/img/default/cc.png"  title="署名-相同方式共享 4.0 国际 (CC BY-SA 4.0)" alt="CC BY-SA 4.0"></a>'
    updateList:
      class: text
      display: [desktop]
      header:
        icon: fa-duotone fa-wrench SUNFLOWER 
        title: 更新日志
      content:
        - 暂无
    # 自定义 站内导航    
    navigation:
      class: grid
      display: [desktop]
      header:
        icon: fa-duotone fa-map-signs POMEGRANATE 
        title: 站内导航
      fixed: true # 固定宽度
      rows:
        - name: 文档笔记
          icon: fa-duotone fa-books GREENSEA
          url:  /page/notes/
        - name: 关于本站
          icon: fa-duotone fa-drafting-compass NEPHRITIS
          url: /page/about/  
        - name: 建站历史
          icon: fa-duotone fa-history POMEGRANATE
          url: /page/timeline/
        - name: 文章归档
          icon: fa-duotone fa-archive PETERRIVE faa-vertical
          url: /archives/
        - name: 小伙伴们
          icon: fa-duotone fa-stamp CONCRETE
          url: /page/friends/
        - name: 十年之约
          icon: fa-duotone fa-glass-cheers PETERRIVE
          url: /page/foreverblog/
    wiki-hexo-theme:
      class: list
      display: [desktop]
      header:
        icon: fa-duotone fa-flower-daffodil ASBESTOS
        title: 笔记本
        url: /page/notes/index.html

tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'
  link:
    placeholder:  /img/default/chrome.png

site_footer:
  layout: [icp, cpy, me, icon]
  lic: '<div class="footerMax560"><p>博客内容遵循 <a target="_blank" rel="external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">「署名-相同方式共享 4.0 国际 (CC BY-SA 4.0)」</a> 协议</p></div>'
  inf: '<div class="footerMax490">本站使用 <a href="https://github.com/volantis-x/hexo-theme-volantis" target="_blank" class="codename" rel="external nofollow noopener noreferrer">Volantis</a> 作为主题 | <span> 由 <a href="https://webify.cloudbase.net" target="_blank" class="codename" rel="external nofollow noopener noreferrer">CloudBase Webify</a> 提供网站托管服务</span></div>'
  icp: '<div class="footerMax490">皖 ICP 备 <a href="https://beian.miit.gov.cn/" target="_blank" rel="nofollow" style="cursor:wait;">2021008088</a> 号 | <span>辽公网安备 <a href="https://www.beian.gov.cn/" rel="nofollow" target="_blank" style="cursor:wait;">21021702000331</a> 号</span></div>'
  cpy: '<div class="footerMax490">Copyright 2018 - 2022 szyink. All Rights Reserved</div>'
  me: '<a href="/">枋柚梓的猫会发光</a> '
  icon: '<i class="fa-duotone fa-heartbeat POMEGRANATE faa-flash faa-slow animated"></i>'

plugins:
  fontawesome: https://static.szyink.com/fontawesome/css/all.min.css
  fancybox:
    css: /js/szyink/fancybox.css
    js: /js/szyink/fancybox.umd.js
  sitesjs:
    enable: false
  friendsjs:
    enable: false
  contributorsjs:
    enable: false
  preload:
    enable: false
    service: instant_page
  lazyload:
    js: /js/szyink/lazyload.min.js
    enable: true
    onlypost: false
  scrollreveal:
    enable: true
  highlightjs:
    enable: false
  fontawesome_animation:
    enable: false
    css: /css/font-awesome-animation.min.css
  wordcount:
    enable: true
  aplayer:
    enable: false
    js:
      aplayer: https://static.szyink.com/common/js/aplayer.min.js
      meting: https://static.szyink.com/common/js/Meting.min.js
    server: tencent
    id: 7716882294
  pjax:
    js: /js/szyink/pjax.min.js
    cover: false
    animation: false
  killOldVersionsOfIE:
    enable: false
  killNoScript:
    enable: false
  darkmode:
    enable: true
  darkmodejs:
    enable: true
  backstretch:
    enable: false
  tag_plugin_load_on_demand:
    enable: false
  message:
    enable: true
    js:  /js/thirdparty/message.js
    css: /css/message.css
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-duotone fa-info-circle light-blue
      quection: fa-duotone fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-SA 4.0 协议。'
      icon: 'fab fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-duotone fa-play light-blue
      pause: fa-duotone fa-pause light-blue
      error: fa-duotone fa-exclamation-square red
    rightmenu:
      enable: true
      notice: true

rightmenus:
  enable: true
  order:
    - plugins.navigation  
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - hr
    - plugins.elementCheck
    - plugins.elementImage
    - menus.links
    - hr
    - plugins.articlePage
    - menus.darkMode
  options:
    iconPrefix: fa-duotone PETERRIVE
    articleShowLink: true
  plugins:
    navigation: 
      - {id: 'left', name: '转到上一页', icon: 'fa-duotone fa-arrow-left PETERRIVE', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-duotone fa-arrow-right PETERRIVE', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-duotone fa-redo PETERRIVE', event: 'window.location.reload()', group: 'navigation'}
      - {id: 'home', name: '回到首页', icon: 'fa-duotone fa-home PETERRIVE', link: '/', group: 'navigation'}
    articlePage:
      - {id: 'printMode', name: '打印页面', icon: 'fa-duotone fa-print TURQUOISE', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-duotone fa-book-open EMERALD', event: 'readMode', group: 'articlePage'}
    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-duotone PETERRIVE fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-duotone PETERRIVE fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-duotone PETERRIVE fa-cut', event: 'copyCut', group: 'inputBox'}
    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-duotone PETERRIVE fa-copy', event: 'copyText', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-duotone PETERRIVE fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: '必应搜索', icon: 'fa-duotone PETERRIVE fa-search', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}
    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-duotone PETERRIVE fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-duotone PETERRIVE fa-link', event: 'copyLink', group: 'elementCheck'}
    elementImage:
      - {id: 'copyImg', name: '复制图片文件', icon: 'fa-duotone PETERRIVE fa-image', event: 'copyImg', group: 'elementImage'}
  menus:
    links:
      - {id: 'notes', name: '文档笔记', icon: 'fa-duotone fa-books GREENSEA', link: '/page/notes/', group: 'link'}
      - {id: 'friends', name: '我的朋友们', icon: 'fa-duotone fa-flower-daffodil AMETHYST', link: '/page/friends/', group: 'link'}
      - {id: 'archive', name: '文章归档', icon: 'fa-duotone fa-globe-asia CONCRETE', link: '/archives/', group: 'link'}
      - {id: 'about', name: '关于我', icon: 'fa-duotone fa-gingerbread-man WISTERIA', link: '/page/about/', group: 'link'}
      - {id: 'info', name: '留言板', icon: 'fa-duotone fa-hand-love ALIZARIN', link: '/page/info/', group: 'link'}
    darkMode: 
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-duotone fa-eclipse-alt WISTERIA', event: 'volantis.dark.toggle()', group: 'darkMode'}

rightmenu: ## fa-solid, fa-regular, fa-light, fa-thin, fa-duotone, fa-brands
  enable: false
  faicon: fa-duotone PETERRIVE      #   笔记   好友     归档   关于
  layout: [copy, navigation, hr, notes, friends, text, about, print, reading, darkmode]
  customPicUrl:
    enable: false  
  darkmode:
    name: 暗黑模式
    icon: fa-duotone fa-eclipse-alt WISTERIA
  print:
    name: 打印页面
    icon: fa-duotone fa-print TURQUOISE
    defaultStyles: true
  reading:
    name: 阅读模式
    icon: fa-duotone fa-book-open EMERALD
  foreverblog:
    name: 十年之约
    icon: fa-duotone fa-glass-cheers PETERRIVE
    url: /page/foreverblog/
  friends:
    name: 我的朋友们
    icon: fa-duotone fa-flower-daffodil AMETHYST
    url: /page/friends/
  info:
    name: 留言板
    icon: fa-duotone fa-fish CARROT
    url: /page/info/
  notes:
    name: 文档笔记
    icon: fa-duotone fa-books GREENSEA
    url: /page/notes/
  text:
    name: 文章归档
    icon: fa-duotone fa-globe-asia CONCRETE
    url: /archives/
  about:
    name: 关于我
    icon: fa-duotone fa-gingerbread-man WISTERIA
    url: /page/about/

color_scheme:
  common:
    selection: '#ddf4ff'
  light:
    site_bg: '#f7f9fe'
    meta: '#666'
    site_footer: '#444'
  dark:
    site_bg: '#21252b'
    site_footer: '#abb2bf'
    card: '#282c34'
    text: '#abb2bf'
    block: '#21252b'
    h1: '#979fa-duotone'
    h2: '#979fa-duotone'
    h3: '#979fa-duotone'
    h4: '#979fa-duotone'
    h5: '#979fa-duotone'
    h6: '#979fa-duotone'
    p: '#abb2bf'

custom_css:
  toc_smooth: true # TOC 目录平滑滚动效果
  cursor:
    enable: true
    text: https://static.szyink.com/common/cursor/text.png
    pointer: https://static.szyink.com/common/cursor/pointer.png
    default: https://static.szyink.com/common/cursor/left_ptr.png
    not-allowed: https://static.szyink.com/common/cursor/circle.png
    zoom-out: https://static.szyink.com/common/cursor/zoom-out.png
    zoom-in: https://static.szyink.com/common/cursor/zoom-in.png
    grab: https://static.szyink.com/common/cursor/openhand.png
  scrollbar:
    size: 4px
    border: 2px  
  fontsize:
    root: 16px
    footnote: .78rem
  body:
    effect: [floatable] # [shadow, floatable, blur]  
  navbar:
    effect: [floatable]
  sidebar:
    effect: [floatable] # [shadow, floatable, blur]  
  max_width: 1080px
  fontfamily:
    logofont:
      fontfamily: 'Roboto, Noto Serif SC,-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif'
      url: ''
    bodyfont:
      fontfamily: '"Noto Serif SC", Roboto,-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif'
      url: ''
    codefont:
      fontfamily: 'JetBrainsMono, Menlo,Monaco,Consolas,Andale Mono,lucida console,Courier New,monospace'
      url: ''

analytics:
  leancloud:
    app_id:
    app_key:

open_graph:
  image: icon/cat192.png

structured_data:
  enable: true
  # 以下是覆盖配置, 默认配置见 scripts/helpers/structured-data/lib/config.js
  data:
    person:
      sns:
        - https://github.com/inkss
    logo:
      path: icon/cat192.png
      width: 192
      height: 192

