InconfontFlag: true

default:
  avatar: /img/default/avatar.svg
  link: /img/default/link.svg
  cover: /img/default/cover.svg
  image: /img/default/image.svg

cdn:
  enable: true
  prefix: https://static.inkss.cn
  set:
    js:
      app: /js/app.js
      rightMenu: /js/plugins/rightMenu.js
      rightMenus: /js/plugins/rightMenus.js
      iconfontInkss: /js/thirdparty/iconfontInkss.js
    css:
      style: /css/style.css

navbar:
  logo:
      img:
      title: INKSS
  search: 想找些什么~
  menu:
    - name: 首页
      icon: fa-light fa-home CARROT faa-vertical
      url: /
    - name: 导航
      icon: fa-light fa-cube NEPHRITIS
      rows:
        - name: 分类列表
          icon: fa-light fa-folder-open ALIZARIN faa-vertical
          url: /categories/
        - name: 文章归档
          icon: fa-light fa-archive PETERRIVE faa-vertical
          url: /archives/
        - name: 个人笔记
          icon: fa-light fa-books CARROT faa-vertical
          url: /page/notes/
    - name: 页面
      icon: fa-light fa-anchor GREENSEA faa-vertical
      rows:
        - name: 站内留言
          icon: fa-light fa-hand-love ALIZARIN faa-vertical
          url: /page/info/
        - name: RSS 订阅
          icon: fa-light fa-rss SUNFLOWER faa-vertical
          url: /page/atom/
        - name: 授权协议
          icon: fa-light fa-universal-access SUNFLOWER faa-vertical
          url: /page/cc/
        - name: 建站历史
          icon: fa-light fa-history ALIZARIN faa-vertical
          url: /page/timeline/
    - name: 更多
      icon: fa-light fa-umbrella POMEGRANATE faa-vertical
      description: 站外资源列表
      rows:
        - name: BT 
          description: 宝塔面板
          icon: fa-light fa-command BELIZEHOLE faa-vertical
          url: https://web.adc.ink/
        - name: Cloud
          description: 可道云
          icon: fa-light fa-cloud WISTERIA faa-vertical
          url: https://cloud.adc.ink/
        - name: Drawio
          icon: fa-light fa-compass-drafting PETERRIVE faa-vertical
          description: Drawio
          url: https://draw.szyink.com/?offline=1
        - name: Hoppscotch
          icon: fa-light fa-staff-aesculapius PETERRIVE faa-vertical
          description: RESTApi
          url: https://hop.szyink.com/cn
        - hr
        - name: Github
          description: 少年，来一份星星不？
          icon: fa-light fa-code-merge WISTERIA faa-vertical
          url: https://github.com/inkss
        - name: Blog
          description: 这是一份记录文字的博客站点
          icon: fa-light fa-stream BELIZEHOLE faa-vertical
          url: https://szyink.com
    - name: 虫洞
      description: 十年之约，探索虫洞
      icon: fa-light fa-bullseye-pointer BELIZEHOLE faa-vertical
      url: https://www.foreverblog.cn/go.html

cover:
  height_scheme: full
  layout_scheme: text
  display:
    home: false
    archive: false
    others: false
  background: /img/main.png
  search: 想找些什么？
  features:
    - name: 关于
      icon: fa-light fa-drafting-compass
      url: /page/about/
    - name: 友链
      icon: fa-light fa-stamp
      url: /page/friends/
    - name: 留言
      icon: fa-light fa-comment-alt-smile
      url: /page/info/
    - name: 归档
      icon: fa-light fa-archive
      url: /archives/

pages:
  friends:
    layout_scheme: traditional 

article:
  preview:
    line_style: hidden
  body:
    top_meta: [author, wordcount, artalkcount]
    bottom_meta: [category, tags, counter]
    meta_library:
      author:
        avatar: https://static.inkss.cn/img/avatar.jpg
        name: 枋柚梓
        url: /
      date:
        icon: fa-light fa-calendar-alt TURQUOISE
      updated:
        icon: fa-light fa-edit GREENSEA
      category:
        icon: fa-light fa-folder-open EMERALD
      counter:
        icon: fa-light fa-eye NEPHRITIS
      walinecount:
        icon: fa-light fa-comment-dots NEPHRITIS
      artalkcount:
        icon: fa-light fa-comment-dots NEPHRITIS
        desc: '条评论' # 条评论
      wordcount:
        icon_wordcount: fa-light fa-keyboard PETERRIVE
        icon_duration: fa-light fa-hourglass-half BELIZEHOLE
      tags:
        icon: fa-light fa-hashtag CARROT
    footer_widget:
      references:
        icon: fa-light fa-quote-left CONCRETE
      copyright:
        enable: true
        content:
          - '博客内容遵循 <a href="/page/cc">署名-非商业性使用-相同方式共享 4.0 国际</a> 协议。'

comments:
  title: <i class='fa-light fa-comments POMEGRANATE'></i> 评论
  service: artalk
  disqus:
    shortname: inkss
  twikoo:
    js: https://static.szyink.com/common/js/twikoo.js # 建议锁定版本 v1.4.4
    envId: twikoo-web-4g84uta0261cb889 # 腾讯云环境id
  beaudar:
    repo: inkss/blog-comments
    branch: master
  artalk:
    js: https://static.szyink.com/storage/artalk/Artalk.js
    css: https://static.szyink.com/storage/artalk/Artalk.css
    server: https://artalk.szyink.com
    imgUploader:
      api: 'https://7bu.top/api/v1/upload'
      token: 'Bearer 58|0Z18ZA8rxh9VjM8PVTvT88gNfKgWvONwQWowIMUe'
      resp: 'data.links.url'

sidebar:
  for_page: [nextsite, artalk, webinfo]
  for_post: [nextsite, toc, webinfo]
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.jpg
      shape: circle # circle, rectangle
      url: /page/about/
      title:
      subtitle: 言语道断，非物所拘。
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fa-light fa-clock WISTERIA
        title: 最近更新
    toc:
      display: [desktop, mobile]
      header:
        icon: fa-light fa-list ASBESTOS
    category:
      display: [desktop]
      header:
        icon: fa-light fa-folder-open ASBESTOS
        url: /categories/
    tagcloud:
      display: [desktop]
      header:
        title: 标签列表
        icon: fa-light fa-tags WISTERIA 
        url: /tags/
      max_font: 24
      min_font: 16
    webinfo:
      display: [desktop]
      header:
        icon: fa-light fa-award NEPHRITIS
      type:
        runtime:
          data: '2018/03/15'
        wordcount:
          unit: ''
        visitcounter:
          siteuv:
            enable: false
          sitepv:
            enable: false
    notice:
      class: text
      display: [desktop]
      header:
        icon: fa-light fa-ghost PETERRIVE 
        title: 公共信息
      content:
        - '嘿，这里是枋柚梓的笔记站，主要是用于记录一些偏专业向的内容，生活向内容请见：[枋柚梓的博客](https://szyink.com/)。'
        - '<a href="https://www.foreverblog.cn/go.html" target="_blank" style="margin-right: 6px;"><img src="/img/default/wormhole.gif" alt="虫洞" style="width:auto;height:31px;border-radius:4px;" title="穿梭虫洞-随机访问十年之约友链博客"></a><a href="/page/cc"><img src="/img/default/cc.png"  title="署名-相同方式共享 4.0 国际 (CC BY-SA 4.0)" alt="CC BY-SA 4.0"></a>'
    updateList:
      class: text
      display: [desktop]
      header:
        icon: fa-light fa-wrench SUNFLOWER 
        title: 更新日志
      content:
        - 暂无
    # 自定义 站内导航    
    navigation:
      class: grid
      display: [desktop]
      header:
        icon: fa-light fa-map-signs POMEGRANATE 
        title: 站内导航
      fixed: true # 固定宽度
      rows:
        - name: ForeverBlog
          icon: fa-light fa-glass-cheers
          url: /page/foreverblog/
        - name: History
          icon: fa-light fa-history
          url: /page/timeline/
        - name: Tags
          icon: fa-light fa-tags
          url:  /tags/
        - name: Hoppscotch
          icon: fa-light fa-staff-aesculapius
          url: https://hop.szyink.com/cn
        - name: Github
          icon: fa-light fa-code-merge
          url: https://github.com/inkss
        - name: RSS
          icon: fa-light fa-rss
          url: /page/atom/

    wiki-hexo-theme:
      class: list
      display: [desktop]
      sticky: true
      header:
        icon: fa-light fa-flower-daffodil ASBESTOS
        title: 《个人笔记》
        url: /page/notes/index.html

tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'
  link:
    placeholder:  /img/default/chrome.png

site_footer:
  layout: [copyright, powered]
  icon: '<i class="fa-light fa-heartbeat POMEGRANATE faa-flash faa-slow animated"></i>'
  copyright: '<span>© 2018 - 2022&nbsp;</span><span><i class="fa-light fa-heartbeat POMEGRANATE faa-flash faa-slow animated"></i></span><span>&nbsp;枋柚梓</span>'
  powered: '<a href="/page/cc/">授权</a> · <a href="/page/policy/">政策</a> | 本站使用 <a href="https://volantis.js.org/" target="_blank">Volantis</a> 主题设计'

plugins:
  fontawesome: https://static.szyink.com/fontawesome/css/all.min.css
  fancybox:
    css: /js/szyink/fancybox.css
    js: /js/szyink/fancybox.umd.js
  sitesjs:
    enable: false
  friendsjs:
    enable: false
  contributorsjs:
    enable: false
  preload:
    enable: false
    service: instant_page
  lazyload:
    js: /js/szyink/lazyload.min.js
    enable: true
    onlypost: false
  scrollreveal:
    enable: false
  highlightjs:
    enable: false
  fontawesome_animation:
    enable: false
    css: /css/font-awesome-animation.min.css
  wordcount:
    enable: true
  aplayer:
    enable: false
    js:
      aplayer: https://static.szyink.com/common/js/aplayer.min.js
      meting: https://static.szyink.com/common/js/Meting.min.js
    server: tencent
    id: 7716882294
  pjax:
    js: /js/szyink/pjax.min.js
    cover: false
    animation: false
  killOldVersionsOfIE:
    enable: false
  killNoScript:
    enable: false
  darkmode:
    enable: true
  darkmodejs:
    enable: true
  tag_plugin_load_on_demand:
    enable: false
  message:
    enable: true
    js:  /js/thirdparty/message.js
    css: /css/message.css
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
    rightmenu:
      enable: true
      notice: true
  parallax:
    enable: true
    images:
      - https://static.szyink.com/storage/hexo/wallhaven-l3pzly.jpg

rightmenus:
  enable: true
  order:
    - plugins.navigation  
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - hr
    - plugins.elementCheck
    - plugins.elementImage
    - menus.prevNext
    - hr
    - menus.links
    - hr
    - plugins.articlePage
    - menus.darkMode
  options:
    iconPrefix: fa-light PETERRIVE
    articleShowLink: false
  plugins:
    navigation: 
      - {id: 'left', name: '转到上一页', icon: 'fa-light fa-arrow-left PETERRIVE', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-light fa-arrow-right PETERRIVE', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-light fa-redo PETERRIVE', event: 'window.location.reload()', group: 'navigation'}
      - {id: 'home', name: '回到首页', icon: 'fa-light fa-home PETERRIVE', link: '/', group: 'navigation'}
    articlePage:
      - {id: 'printMode', name: '打印页面', icon: 'fa-light fa-print TURQUOISE', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-light fa-book-open EMERALD', event: 'readMode', group: 'articlePage'}
    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-light PETERRIVE fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-light PETERRIVE fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-light PETERRIVE fa-cut', event: 'copyCut', group: 'inputBox'}
    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-light PETERRIVE fa-copy', event: 'copyText', group: 'seletctText'}
      - {id: 'html2md', name: '复制为 MD', icon: 'fa-light PETERRIVE fa-file-signature', event: 'volantis.rightmenu.html2md()', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-light PETERRIVE fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: '必应搜索', icon: 'fa-light PETERRIVE fa-search', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}
    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-light PETERRIVE fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-light PETERRIVE fa-link', event: 'copyLink', group: 'elementCheck'}
    elementImage:
      - {id: 'copyImg', name: '复制图片文件', icon: 'fa-light PETERRIVE fa-image', event: 'copyImg', group: 'elementImage'}
  menus:
    links:
      - {id: 'notes', name: '文档笔记', icon: 'fa-light fa-books GREENSEA', link: '/page/notes/', group: 'link'}
      - {id: 'friends', name: '我的朋友们', icon: 'fa-light fa-flower-daffodil AMETHYST', link: '/page/friends/', group: 'link'}
      - {id: 'archive', name: '文章归档', icon: 'fa-light fa-globe-asia CONCRETE', link: '/archives/', group: 'link'}
      - {id: 'about', name: '关于我', icon: 'fa-light fa-gingerbread-man WISTERIA', link: '/page/about/', group: 'link'}
      - {id: 'info', name: '留言板', icon: 'fa-light fa-hand-love ALIZARIN', link: '/page/info/', group: 'link'}
    darkMode: 
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-light fa-eclipse-alt WISTERIA', event: 'volantis.dark.toggle()', group: 'darkMode'}
    prevNext:
      - {id: 'prev', name: '查看上一篇', icon: 'fa-light fa-angles-left PETERRIVE', event: "volantis.rightmenu.jump('prev')", group: 'prevNext'}
      - {id: 'next', name: '查看下一篇', icon: 'fa-light fa-angles-right PETERRIVE', event: "volantis.rightmenu.jump('next')", group: 'prevNext'}

rightmenu: ## fa-solid, fa-regular, fa-light, fa-thin, fa-light, fa-brands
  enable: false
  faicon: fa-light PETERRIVE      #   笔记   好友     归档   关于
  layout: [copy, navigation, hr, notes, friends, text, about, print, reading, darkmode]
  customPicUrl:
    enable: false  
  darkmode:
    name: 暗黑模式
    icon: fa-light fa-eclipse-alt WISTERIA
  print:
    name: 打印页面
    icon: fa-light fa-print TURQUOISE
    defaultStyles: true
  reading:
    name: 阅读模式
    icon: fa-light fa-book-open EMERALD
  foreverblog:
    name: 十年之约
    icon: fa-light fa-glass-cheers PETERRIVE
    url: /page/foreverblog/
  friends:
    name: 我的朋友们
    icon: fa-light fa-flower-daffodil AMETHYST
    url: /page/friends/
  info:
    name: 留言板
    icon: fa-light fa-fish CARROT
    url: /page/info/
  notes:
    name: 文档笔记
    icon: fa-light fa-books GREENSEA
    url: /page/notes/
  text:
    name: 文章归档
    icon: fa-light fa-globe-asia CONCRETE
    url: /archives/
  about:
    name: 关于我
    icon: fa-light fa-gingerbread-man WISTERIA
    url: /page/about/

color_scheme:
  dark:
    site_bd: '#14171a'

custom_css:
  toc_smooth: true # TOC 目录平滑滚动效果
  cursor:
    enable: true
    text: https://static.szyink.com/common/cursor/text.png
    pointer: https://static.szyink.com/common/cursor/pointer.png
    default: https://static.szyink.com/common/cursor/left_ptr.png
    not-allowed: https://static.szyink.com/common/cursor/circle.png
    zoom-out: https://static.szyink.com/common/cursor/zoom-out.png
    zoom-in: https://static.szyink.com/common/cursor/zoom-in.png
    grab: https://static.szyink.com/common/cursor/openhand.png
  scrollbar:
    size: 4px
    border: 2px  
  fontsize:
    root: 16px
    footnote: .78rem
  body:
    effect: [floatable, cus-shadow] # [shadow, floatable, blur]  
  navbar:
    effect: [floatable, cus-shadow]
    height: 0px
  sidebar:
    effect: [floatable, cus-shadow] # [shadow, floatable, blur]  
  max_width: 1080px
  fontfamily:
    logofont:
      fontfamily: 'Roboto, Noto Serif SC,-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif'
      url: ''
    bodyfont:
      fontfamily: '"Noto Serif SC", Roboto,-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif'
      url: ''
    codefont:
      fontfamily: 'JetBrainsMono, Menlo,Monaco,Consolas,Andale Mono,lucida console,Courier New,monospace'
      url: ''

analytics:
  leancloud:
    app_id:
    app_key:

open_graph:
  image: icon/cat192.png

structured_data:
  enable: true
  # 以下是覆盖配置, 默认配置见 scripts/helpers/structured-data/lib/config.js
  data:
    person:
      sns:
        - https://github.com/inkss
    logo:
      path: icon/cat192.png
      width: 192
      height: 192

