name: '日志打印'
on: workflow_dispatch

jobs:
  syncGit:
    runs-on: self-hosted
    name: '基础环境展示'
    env:
      GPG_TTY: $(tty)
    steps:
      - name: '打印环境变量'
        run: |
          echo "Home: ${HOME}"
          echo "PATH: ${PATH}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
