name: 'Hexo 部署 - Webify'
on: workflow_dispatch

jobs:
  buildToGit:
    runs-on: ubuntu-latest
    name: '部署博客：分发'
    env:
      GPG_TTY: $(tty)
    steps:
      - name: '显示服务地址'
        run: |    
          curl cip.cc  
      - name: '同步仓库内容'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: '设定环境版本'
        uses: actions/setup-node@master
        with:
          node-version: "14.17.0"
      - name: '缓存依赖环境'
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-     
      - name: '安装依赖环境'
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: '用户加密配置'
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SZYINK_PRIVATE }}
          passphrase: ${{ secrets.GPG_SZYINK_PASSWD }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          git-push-gpgsign: true
      - name: '生成网站源码'
        run: |
          cat _other.yml >> _config.yml
          git config --global user.name "sssszy"
          git config --global user.email ${{ secrets.EMAIL_OUTLOOK }}
          git config --global commit.gpgsign true
          git config --global user.signingkey 2616D79259B96889
          npm run rebuild
      - name: '部署博客'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          external_repository: sssszy/blog
          force_orphan: true
          publish_branch: main
          user_name: 'sssszy'
          user_email: ${{ secrets.EMAIL_OUTLOOK }}
          personal_token: ${{ secrets.SZYINK_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
